### PR TITLE
Fix impossibility to retry or forget failed jobs by ID

### LINKED ISSUE #12: Can't retry or forget failed job by it ID
## Describe the bug

Can't retry or forget failed job by ID

For example, we have failed job:
```
$ ./artisan queue:failed
```
```
+----------+------------+-----------------+-------------------+---------------------+
| ID       | Connection | Queue           | Class             | Failed At           |
+----------+------------+-----------------+-------------------+---------------------+
| 87254153 | rabbitmq   | processing-jobs | App\Jobs\SomeJob  | 2019-12-20 07:36:36 |
+----------+------------+-----------------+-------------------+---------------------+
```

Let's try to retry this job:

```
$ ./artisan queue:retry 87254153
```
```
Unable to find failed job with ID [87254153].
```

Or forget this job:

```
$ ./artisan queue:forget 87254153
```
```
No failed job matches the given ID.
```
### Expected behaviour

I expect that job with given ID will be retried or forgot

### Actual behaviour

`RabbitQueueFailedJobProvider` can't find job with given ID

### Steps to reproduce the behavior:
Make simple job that should fail:

```php
class SomeJob implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    public function handle(): void
    {
        $this->fail(new \Exception('test'));
    }
}
```
Then dispatch this job:
```php
SomeJob::dispatch();
```
It'll fail. Then try to retry this failed job by it ID.

## System information

> Please, complete the following information:

 - PHP version(s): [e.g. `7.2.14`]
 - Package version(s): [e.g. `2.3.0`]

### PR DESCRIPTION
**Pull request by Reallife**
| Q             | A
| ------------- | ---
| Bug fix?      | Yes
| New feature?  | No

## Description

Fix impossibility to retry or forget failed jobs by ID

Fixes #12 

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I wrote unit tests for my code _(if tests is required for my changes)_
- [x] I have made changes in [CHANGELOG.md](https://github.com/avto-dev/amqp-rabbit-laravel-queue/blob/master/CHANGELOG.md) file

### CODE REVIEW

File: src/Failed/RabbitQueueFailedJobProvider.php [hunk 1]
```diff
@@ -120,7 +120,7 @@ public static function generateMessageId(...$arguments): int
     public function find($id)
     {
         foreach ($this->all() as $job) {
-            if (\property_exists($job, 'id') && $job->id === $id) {
+            if (\property_exists($job, 'id') && \is_numeric($id) && ((int) $job->id) === ((int) $id)) {
```
Comment (Reallife) [inline src/Failed/RabbitQueueFailedJobProvider.php:123]: I'm not sure that method's parameter `$id` always should be numeric (`123` or `"123"`). But message's id generation method seems to return integer values. Maybe no need to check `\is_numeric(...)`. Need to discuss.
